const initCoins = {
  coins: [
    "KRW-BTC",
    "KRW-ETH",
    "KRW-XRP",
    "KRW-ADA",
    "KRW-DOGE",
    "KRW-GRS",
    "KRW-POLY",
    "KRW-ETC",
    "KRW-HUNT",
    "KRW-CHZ",
    "KRW-WEMIX",
    "KRW-HIVE",
    "KRW-ALGO",
    "KRW-ATOM",
    "KRW-PUNDIX",
    "KRW-SOL",
    "KRW-SAND",
    "KRW-MATIC",
    "KRW-LINK",
    "KRW-TRX",
    "KRW-BCH",
    "KRW-WAVES",
    "KRW-XEC",
    "KRW-AXS",
    "KRW-MANA",
    "KRW-REP",
    "KRW-NEAR",
    "KRW-FLOW",
    "KRW-MBL",
    "KRW-KNC",
    "KRW-PLA",
    "KRW-EOS",
    "KRW-XLM",
    "KRW-ZIL",
    "KRW-BTG",
    "KRW-KAVA",
    "KRW-STEEM",
    "KRW-MFT",
    "KRW-QKC",
    "KRW-DOT",
    "KRW-GLM",
    "KRW-XEM",
    "KRW-LOOM",
    "KRW-BORA",
    "KRW-SXP",
    "KRW-NEO",
    "KRW-AERGO",
    "KRW-STX",
    "KRW-VET",
    "KRW-HBAR",
    "KRW-WAXP",
    "KRW-JST",
    "KRW-UPP",
    "KRW-GMT",
    "KRW-AVAX",
    "KRW-ANKR",
    "KRW-NU",
    "KRW-SRM",
    "KRW-ORBS",
    "KRW-STORJ",
    "KRW-STPT",
    "KRW-HUM",
    "KRW-TFUEL",
    "KRW-AAVE",
    "KRW-MTL",
    "KRW-ARK",
    "KRW-POWR",
    "KRW-BSV",
    "KRW-STRAX",
    "KRW-STMX",
    "KRW-CVC",
    "KRW-RFR",
    "KRW-THETA",
    "KRW-ENJ",
    "KRW-ONG",
    "KRW-IOTA",
    "KRW-SNT",
    "KRW-T",
    "KRW-TT",
    "KRW-GAS",
    "KRW-ZRX",
    "KRW-ELF",
    "KRW-MED",
    "KRW-XTZ",
    "KRW-LSK",
    "KRW-BTT",
    "KRW-AQT",
    "KRW-SSX",
    "KRW-DAWN",
    "KRW-SBD",
    "KRW-ARDR",
    "KRW-DKA",
    "KRW-ARDR",
    "KRW-DKA",
    "KRW-MOC",
    "KRW-MLK",
    "KRW-ONT",
    "KRW-CELO",
    "KRW-OMG",
    "KRW-CBK",
    "KRW-SC",
    "KRW-ICX",
    "KRW-IQ",
    "KRW-BAT",
    "KRW-META",
    "KRW-TON",
    "KRW-IOST",
  ],
  coinsName: {
    "KRW-BTC": "비트코인",
    "KRW-ETH": "이더리움",
    "KRW-XRP": "리플",
    "KRW-ADA": "에이다",
    "KRW-DOGE": "도지코인",
    "KRW-GRS": "그로스톨코인",
    "KRW-POLY": "폴리매쓰",
    "KRW-ETC": "이더리움 클래식",
    "KRW-HUNT": "헌트",
    "KRW-CHZ": "칠리즈",
    "KRW-WEMIX": "위믹스",
    "KRW-HIVE": "하이브",
    "KRW-ALGO": "알고랜드",
    "KRW-ATOM": "코스모스",
    "KRW-PUNDIX": "펀디엑스",
    "KRW-SOL": "솔라나",
    "KRW-SAND": "샌드박스",
    "KRW-MATIC": "폴리곤",
    "KRW-LINK": "링크",
    "KRW-TRX": "트론",
    "KRW-BCH": "비트코인캐시",
    "KRW-WAVES": "웨이브",
    "KRW-XEC": "이캐시",
    "KRW-AXS": "엑시인피니티",
    "KRW-MANA": "디센트럴랜드",
    "KRW-REP": "어거",
    "KRW-NEAR": "니어프로토콜",
    "KRW-FLOW": "플로우",
    "KRW-MBL": "무비블록",
    "KRW-KNC": "카이버네트워크",
    "KRW-PLA": "플레이댑",
    "KRW-EOS": "이오스",
    "KRW-XLM": "스텔라루멘",
    "KRW-ZIL": "질리카",
    "KRW-BTG": "비트코인골드",
    "KRW-KAVA": "카바",
    "KRW-STEEM": "스팀",
    "KRW-MFT": "메인프레임",
    "KRW-QKC": "쿼크체인",
    "KRW-DOT": "폴카닷",
    "KRW-GLM": "골렘",
    "KRW-XEM": "넴",
    "KRW-LOOM": "룸네트워크",
    "KRW-BORA": "보라",
    "KRW-SXP": "솔라",
    "KRW-NEO": "네오",
    "KRW-AERGO": "아르고",
    "KRW-STX": "스택스",
    "KRW-VET": "비체인",
    "KRW-HBAR": "헤데라",
    "KRW-WAXP": "왁스",
    "KRW-JST": "저스트",
    "KRW-UPP": "센티넬프로토콜",
    "KRW-GMT": "스테픈",
    "KRW-AVAX": "아발란체",
    "KRW-ANKR": "앵커",
    "KRW-NU": "누싸이퍼",
    "KRW-SRM": "세럼",
    "KRW-ORBS": "오브스",
    "KRW-STORJ": "스토리지",
    "KRW-STPT": "에스티피",
    "KRW-HUM": "휴먼이스케이프",
    "KRW-TFUEL": "세타퓨엘",
    "KRW-AAVE": "에이브",
    "KRW-MTL": "메탈",
    "KRW-ARK": "아크",
    "KRW-POWR": "파워렛저",
    "KRW-BSV": "비트코인에스브이",
    "KRW-STRAX": "스트라티스",
    "KRW-STMX": "스톰엑스",
    "KRW-CVC": "시빅",
    "KRW-RFR": "리퍼리움",
    "KRW-THETA": "세타토큰",
    "KRW-ENJ": "엔진코인",
    "KRW-ONG": "온톨로지",
    "KRW-IOTA": "아이오타",
    "KRW-SNT": "스테이터스네트워크토큰",
    "KRW-T": "쓰레스홀드",
    "KRW-TT": "썬더코어",
    "KRW-GAS": "가스",
    "KRW-ZRX": "제로엑스",
    "KRW-ELF": "엘프",
    "KRW-MED": "메디블록",
    "KRW-XTZ": "테조스",
    "KRW-LSK": "리스크",
    "KRW-BTT": "비트토렌트",
    "KRW-AQT": "알파쿼크",
    "KRW-SSX": "썸씽",
    "KRW-DAWN": "던프로토콜",
    "KRW-SBD": "스팀달러",
    "KRW-ARDR": "아더",
    "KRW-DKA": "디카르고",
    "KRW-MOC": "모스코인",
    "KRW-MLK": "밀크",
    "KRW-ONT": "온톨로지",
    "KRW-CELO": "셀로",
    "KRW-OMG": "오미세고",
    "KRW-CBK": "코박토큰",
    "KRW-SC": "시아코인",
    "KRW-ICX": "아이콘",
    "KRW-IQ": "에브리피디아",
    "KRW-BAT": "베이직어텍션토큰",
    "KRW-META": "메타디움",
    "KRW-TON": "톤",
    "KRW-IOST": "아이오에스티",
  },
};

/**
 ticker = {
 trade_price: 0.0593
 change:"RISE",
 change_rate : 0.0794392523,
 change_price : 0.0051,
 acc_trade_price_24h: 104006518808.96524
 }
 */

const coinsPrice = [];

for (const [key, name] of Object.entries(initCoins.coinsName)) {
  coinsPrice.push({
    name: `${name}`,
    imgUrl: `https://static.upbit.com/logos/${key}.png`,
    code: `${key}`,
    trade_price: 0.0593,
    change: "RISE",
    change_rate: 0.0794392523,
    change_price: 0.0051,
    acc_trade_price_24h: 104006518808.96524,
  });
}

export { coinsPrice };
