export const ticker = {
  tickers: [
    "BTC",
    "ETH",
    "XRP",
    "ADA",
    "DOGE",
    "GRS",
    "POLY",
    "ETC",
    "HUNT",
    "CHZ",
    "WEMIX",
    "HIVE",
    "ALGO",
    "ATOM",
    "PUNDIX",
    "SOL",
    "SAND",
    "MATIC",
    "LINK",
    "TRX",
    "BCH",
    "WAVES",
    "XEC",
    "AXS",
    "MANA",
    "REP",
    "NEAR",
    "FLOW",
    "MBL",
    "KNC",
    "PLA",
    "EOS",
    "XLM",
    "ZIL",
    "BTG",
    "KAVA",
    "STEEM",
    "MFT",
    "QKC",
    "DOT",
    "GLM",
    "XEM",
    "LOOM",
    "BORA",
    "SXP",
    "NEO",
    "AERGO",
    "STX",
    "VET",
    "HBAR",
    "WAXP",
    "JST",
    "UPP",
    "GMT",
    "AVAX",
    "ANKR",
    "NU",
    "SRM",
    "ORBS",
    "STORJ",
    "STPT",
    "HUM",
    "TFUEL",
    "AAVE",
    "MTL",
    "ARK",
    "POWR",
    "BSV",
    "STRAX",
    "STMX",
    "CVC",
    "RFR",
    "THETA",
    "ENJ",
    "ONG",
    "IOTA",
    "SNT",
    "T",
    "TT",
    "GAS",
    "ZRX",
    "ELF",
    "MED",
    "XTZ",
    "LSK",
    "BTT",
    "AQT",
    "SSX",
    "DAWN",
    "SBD",
    "ARDR",
    "DKA",
    "ARDR",
    "DKA",
    "MOC",
    "MLK",
    "ONT",
    "CELO",
    "OMG",
    "CBK",
    "SC",
    "ICX",
    "IQ",
    "BAT",
    "META",
    "TON",
    "IOST",
  ],
  initTicker: {
    BTC: false,
    ETH: false,
    XRP: false,
    ADA: false,
    DOGE: false,
    GRS: false,
    POLY: false,
    ETC: false,
    HUNT: false,
    CHZ: false,
    WEMIX: false,
    HIVE: false,
    ALGO: false,
    ATOM: false,
    PUNDIX: false,
    SOL: false,
    SAND: false,
    MATIC: false,
    LINK: false,
    TRX: false,
    BCH: false,
    WAVES: false,
    XEC: false,
    AXS: false,
    MANA: false,
    REP: false,
    NEAR: false,
    FLOW: false,
    MBL: false,
    KNC: false,
    PLA: false,
    EOS: false,
    XLM: false,
    ZIL: false,
    BTG: false,
    KAVA: false,
    STEEM: false,
    MFT: false,
    QKC: false,
    DOT: false,
    GLM: false,
    XEM: false,
    LOOM: false,
    BORA: false,
    SXP: false,
    NEO: false,
    AERGO: false,
    STX: false,
    VET: false,
    HBAR: false,
    WAXP: false,
    JST: false,
    UPP: false,
    GMT: false,
    AVAX: false,
    ANKR: false,
    NU: false,
    SRM: false,
    ORBS: false,
    STORJ: false,
    STPT: false,
    HUM: false,
    TFUEL: false,
    AAVE: false,
    MTL: false,
    ARK: false,
    POWR: false,
    BSV: false,
    STRAX: false,
    STMX: false,
    CVC: false,
    RFR: false,
    THETA: false,
    ENJ: false,
    ONG: false,
    IOTA: false,
    SNT: false,
    T: false,
    TT: false,
    GAS: false,
    ZRX: false,
    ELF: false,
    MED: false,
    XTZ: false,
    LSK: false,
    BTT: false,
    AQT: false,
    SSX: false,
    DAWN: false,
    SBD: false,
    ARDR: false,
    DKA: false,
    ARDR: false,
    DKA: false,
    MOC: false,
    MLK: false,
    ONT: false,
    CELO: false,
    OMG: false,
    CBK: false,
    SC: false,
    ICX: false,
    IQ: false,
    BAT: false,
    META: false,
    TON: false,
    IOST: false,
  },
  tickerContent: {
    BTC: { name: "비트코인", url: "https://static.upbit.com/logos/BTC.png" },
    ETH: { name: "이더리움", url: "https://static.upbit.com/logos/ETH.png" },
    XRP: { name: "리플", url: "https://static.upbit.com/logos/XRP.png" },
    ADA: { name: "에이다", url: "https://static.upbit.com/logos/ADA.png" },
    DOGE: { name: "도지코인", url: "https://static.upbit.com/logos/DOGE.png" },
    GRS: { name: "그로스톨코인", url: "https://static.upbit.com/logos/GRS.png" },
    POLY: { name: "", url: "https://static.upbit.com/logos/POLY.png" },
    ETC: { name: "", url: "https://static.upbit.com/logos/ETC.png" },
    HUNT: { name: "", url: "https://static.upbit.com/logos/HUNT.png" },
    CHZ: { name: "", url: "https://static.upbit.com/logos/CHZ.png" },
    WEMIX: { name: "", url: "https://static.upbit.com/logos/WEMIX.png" },
    HIVE: { name: "", url: "https://static.upbit.com/logos/HIVE.png" },
    ALGO: { name: "", url: "https://static.upbit.com/logos/ALGO.png" },
    ATOM: { name: "", url: "https://static.upbit.com/logos/ATOM.png" },
    PUNDIX: { name: "", url: "https://static.upbit.com/logos/PUNDIX.png" },
    SOL: { name: "", url: "https://static.upbit.com/logos/SOL.png" },
    SAND: { name: "", url: "https://static.upbit.com/logos/SAND.png" },
    MATIC: { name: "", url: "https://static.upbit.com/logos/MATIC.png" },
    LINK: { name: "", url: "https://static.upbit.com/logos/LINK.png" },
    TRX: { name: "", url: "https://static.upbit.com/logos/TRX.png" },
    BCH: { name: "", url: "https://static.upbit.com/logos/BCH.png" },
    WAVES: { name: "", url: "https://static.upbit.com/logos/WAVES.png" },
    XEC: { name: "", url: "https://static.upbit.com/logos/XEC.png" },
    AXS: { name: "", url: "https://static.upbit.com/logos/AXS.png" },
    MANA: { name: "", url: "https://static.upbit.com/logos/MANA.png" },
    REP: { name: "", url: "https://static.upbit.com/logos/REP.png" },
    NEAR: { name: "", url: "https://static.upbit.com/logos/NEAR.png" },
    FLOW: { name: "", url: "https://static.upbit.com/logos/FLOW.png" },
    MBL: { name: "", url: "https://static.upbit.com/logos/MBL.png" },
    KNC: { name: "", url: "https://static.upbit.com/logos/KNC.png" },
    PLA: { name: "", url: "https://static.upbit.com/logos/PLA.png" },
    EOS: { name: "", url: "https://static.upbit.com/logos/EOS.png" },
    XLM: { name: "", url: "https://static.upbit.com/logos/XLM.png" },
    ZIL: { name: "", url: "https://static.upbit.com/logos/ZIL.png" },
    BTG: { name: "", url: "https://static.upbit.com/logos/BTG.png" },
    KAVA: { name: "", url: "https://static.upbit.com/logos/KAVA.png" },
    STEEM: { name: "", url: "https://static.upbit.com/logos/STEEM.png" },
    MFT: { name: "", url: "https://static.upbit.com/logos/MFT.png" },
    QKC: { name: "", url: "https://static.upbit.com/logos/QKC.png" },
    DOT: { name: "", url: "https://static.upbit.com/logos/DOT.png" },
    GLM: { name: "", url: "https://static.upbit.com/logos/GLM.png" },
    XEM: { name: "", url: "https://static.upbit.com/logos/XEM.png" },
    LOOM: { name: "", url: "https://static.upbit.com/logos/LOOM.png" },
    BORA: { name: "", url: "https://static.upbit.com/logos/BORA.png" },
    SXP: { name: "", url: "https://static.upbit.com/logos/SXP.png" },
    NEO: { name: "", url: "https://static.upbit.com/logos/NEO.png" },
    AERGO: { name: "", url: "https://static.upbit.com/logos/AERGO.png" },
    STX: { name: "", url: "https://static.upbit.com/logos/STX.png" },
    VET: { name: "", url: "https://static.upbit.com/logos/VET.png" },
    HBAR: { name: "", url: "https://static.upbit.com/logos/HBAR.png" },
    WAXP: { name: "", url: "https://static.upbit.com/logos/WAXP.png" },
    JST: { name: "", url: "https://static.upbit.com/logos/JST.png" },
    UPP: { name: "", url: "https://static.upbit.com/logos/UPP.png" },
    GMT: { name: "", url: "https://static.upbit.com/logos/GMT.png" },
    AVAX: { name: "", url: "https://static.upbit.com/logos/AVAX.png" },
    ANKR: { name: "", url: "https://static.upbit.com/logos/ANKR.png" },
    NU: { name: "", url: "https://static.upbit.com/logos/NU.png" },
    SRM: { name: "", url: "https://static.upbit.com/logos/SRM.png" },
    ORBS: { name: "", url: "https://static.upbit.com/logos/ORBS.png" },
    STORJ: { name: "", url: "https://static.upbit.com/logos/STORJ.png" },
    STPT: { name: "", url: "https://static.upbit.com/logos/STPT.png" },
    HUM: { name: "", url: "https://static.upbit.com/logos/HUM.png" },
    TFUEL: { name: "", url: "https://static.upbit.com/logos/TFUEL.png" },
    AAVE: { name: "", url: "https://static.upbit.com/logos/AAVE.png" },
    MTL: { name: "", url: "https://static.upbit.com/logos/MTL.png" },
    ARK: { name: "", url: "https://static.upbit.com/logos/ARK.png" },
    POWR: { name: "", url: "https://static.upbit.com/logos/POWR.png" },
    BSV: { name: "", url: "https://static.upbit.com/logos/BSV.png" },
    STRAX: { name: "", url: "https://static.upbit.com/logos/STRAX.png" },
    STMX: { name: "", url: "https://static.upbit.com/logos/STMX.png" },
    CVC: { name: "", url: "https://static.upbit.com/logos/CVC.png" },
    RFR: { name: "", url: "https://static.upbit.com/logos/RFR.png" },
    THETA: { name: "", url: "https://static.upbit.com/logos/THETA.png" },
    ENJ: { name: "", url: "https://static.upbit.com/logos/ENJ.png" },
    ONG: { name: "", url: "https://static.upbit.com/logos/ONG.png" },
    IOTA: { name: "", url: "https://static.upbit.com/logos/IOTA.png" },
    SNT: { name: "", url: "https://static.upbit.com/logos/SNT.png" },
    T: { name: "", url: "https://static.upbit.com/logos/T.png" },
    TT: { name: "", url: "https://static.upbit.com/logos/TT.png" },
    GAS: { name: "", url: "https://static.upbit.com/logos/GAS.png" },
    ZRX: { name: "", url: "https://static.upbit.com/logos/ZRX.png" },
    ELF: { name: "", url: "https://static.upbit.com/logos/ELF.png" },
    MED: { name: "", url: "https://static.upbit.com/logos/MED.png" },
    XTZ: { name: "", url: "https://static.upbit.com/logos/XTZ.png" },
    LSK: { name: "", url: "https://static.upbit.com/logos/LSK.png" },
    BTT: { name: "", url: "https://static.upbit.com/logos/BTT.png" },
    AQT: { name: "", url: "https://static.upbit.com/logos/AQT.png" },
    SSX: { name: "", url: "https://static.upbit.com/logos/SSX.png" },
    DAWN: { name: "", url: "https://static.upbit.com/logos/DAWN.png" },
    SBD: { name: "", url: "https://static.upbit.com/logos/SBD.png" },
    ARDR: { name: "", url: "https://static.upbit.com/logos/ARDR.png" },
    DKA: { name: "", url: "https://static.upbit.com/logos/DKA.png" },
    ARDR: { name: "", url: "https://static.upbit.com/logos/ARDR.png" },
    DKA: { name: "", url: "https://static.upbit.com/logos/DKA.png" },
    MOC: { name: "", url: "https://static.upbit.com/logos/MOC.png" },
    MLK: { name: "", url: "https://static.upbit.com/logos/MLK.png" },
    ONT: { name: "", url: "https://static.upbit.com/logos/ONT.png" },
    CELO: { name: "", url: "https://static.upbit.com/logos/CELO.png" },
    OMG: { name: "", url: "https://static.upbit.com/logos/OMG.png" },
    CBK: { name: "", url: "https://static.upbit.com/logos/CBK.png" },
    SC: { name: "", url: "https://static.upbit.com/logos/SC.png" },
    ICX: { name: "", url: "https://static.upbit.com/logos/ICX.png" },
    IQ: { name: "", url: "https://static.upbit.com/logos/IQ.png" },
    BAT: { name: "", url: "https://static.upbit.com/logos/BAT.png" },
    META: { name: "", url: "https://static.upbit.com/logos/META.png" },
    TON: { name: "", url: "https://static.upbit.com/logos/TON.png" },
    IOST: { name: "", url: "https://static.upbit.com/logos/IOST.png" },
  },
};
