export const ticker = {
  tickers: [
    "BTC",
    "ETH",
    "XRP",
    "ADA",
    "DOGE",
    "GRS",
    "POLY",
    "ETC",
    "HUNT",
    "CHZ",
    "WEMIX",
    "HIVE",
    "ALGO",
    "ATOM",
    "PUNDIX",
    "SOL",
    "SAND",
    "MATIC",
    "LINK",
    "TRX",
    "BCH",
    "WAVES",
    "XEC",
    "AXS",
    "MANA",
    "REP",
    "NEAR",
    "FLOW",
    "MBL",
    "KNC",
    "PLA",
    "EOS",
    "XLM",
    "ZIL",
    "BTG",
    "KAVA",
    "STEEM",
    "MFT",
    "QKC",
    "DOT",
    "GLM",
    "XEM",
    "LOOM",
    "BORA",
    "SXP",
    "NEO",
    "AERGO",
    "STX",
    "VET",
    "HBAR",
    "WAXP",
    "JST",
    "UPP",
    "GMT",
    "AVAX",
    "ANKR",
    "NU",
    "SRM",
    "ORBS",
    "STORJ",
    "STPT",
    "HUM",
    "TFUEL",
    "AAVE",
    "MTL",
    "ARK",
    "POWR",
    "BSV",
    "STRAX",
    "STMX",
    "CVC",
    "RFR",
    "THETA",
    "ENJ",
    "ONG",
    "IOTA",
    "SNT",
    "T",
    "TT",
    "GAS",
    "ZRX",
    "ELF",
    "MED",
    "XTZ",
    "LSK",
    "BTT",
    "AQT",
    "SSX",
    "DAWN",
    "SBD",
    "ARDR",
    "DKA",
    "ARDR",
    "DKA",
    "MOC",
    "MLK",
    "ONT",
    "CELO",
    "OMG",
    "CBK",
    "SC",
    "ICX",
    "IQ",
    "BAT",
    "META",
    "TON",
    "IOST",
  ],
  initTicker: {
    BTC: false,
    ETH: false,
    XRP: false,
    ADA: false,
    DOGE: false,
    GRS: false,
    POLY: false,
    ETC: false,
    HUNT: false,
    CHZ: false,
    WEMIX: false,
    HIVE: false,
    ALGO: false,
    ATOM: false,
    PUNDIX: false,
    SOL: false,
    SAND: false,
    MATIC: false,
    LINK: false,
    TRX: false,
    BCH: false,
    WAVES: false,
    XEC: false,
    AXS: false,
    MANA: false,
    REP: false,
    NEAR: false,
    FLOW: false,
    MBL: false,
    KNC: false,
    PLA: false,
    EOS: false,
    XLM: false,
    ZIL: false,
    BTG: false,
    KAVA: false,
    STEEM: false,
    MFT: false,
    QKC: false,
    DOT: false,
    GLM: false,
    XEM: false,
    LOOM: false,
    BORA: false,
    SXP: false,
    NEO: false,
    AERGO: false,
    STX: false,
    VET: false,
    HBAR: false,
    WAXP: false,
    JST: false,
    UPP: false,
    GMT: false,
    AVAX: false,
    ANKR: false,
    NU: false,
    SRM: false,
    ORBS: false,
    STORJ: false,
    STPT: false,
    HUM: false,
    TFUEL: false,
    AAVE: false,
    MTL: false,
    ARK: false,
    POWR: false,
    BSV: false,
    STRAX: false,
    STMX: false,
    CVC: false,
    RFR: false,
    THETA: false,
    ENJ: false,
    ONG: false,
    IOTA: false,
    SNT: false,
    T: false,
    TT: false,
    GAS: false,
    ZRX: false,
    ELF: false,
    MED: false,
    XTZ: false,
    LSK: false,
    BTT: false,
    AQT: false,
    SSX: false,
    DAWN: false,
    SBD: false,
    ARDR: false,
    DKA: false,
    ARDR: false,
    DKA: false,
    MOC: false,
    MLK: false,
    ONT: false,
    CELO: false,
    OMG: false,
    CBK: false,
    SC: false,
    ICX: false,
    IQ: false,
    BAT: false,
    META: false,
    TON: false,
    IOST: false,
  },
  tickerContent: {
    BTC: { name: "", url: "" },
    ETH: { name: "", url: "" },
    XRP: { name: "", url: "" },
    ADA: { name: "", url: "" },
    DOGE: { name: "", url: "" },
    GRS: { name: "", url: "" },
    POLY: { name: "", url: "" },
    ETC: { name: "", url: "" },
    HUNT: { name: "", url: "" },
    CHZ: { name: "", url: "" },
    WEMIX: { name: "", url: "" },
    HIVE: { name: "", url: "" },
    ALGO: { name: "", url: "" },
    ATOM: { name: "", url: "" },
    PUNDIX: { name: "", url: "" },
    SOL: { name: "", url: "" },
    SAND: { name: "", url: "" },
    MATIC: { name: "", url: "" },
    LINK: { name: "", url: "" },
    TRX: { name: "", url: "" },
    BCH: { name: "", url: "" },
    WAVES: { name: "", url: "" },
    XEC: { name: "", url: "" },
    AXS: { name: "", url: "" },
    MANA: { name: "", url: "" },
    REP: { name: "", url: "" },
    NEAR: { name: "", url: "" },
    FLOW: { name: "", url: "" },
    MBL: { name: "", url: "" },
    KNC: { name: "", url: "" },
    PLA: { name: "", url: "" },
    EOS: { name: "", url: "" },
    XLM: { name: "", url: "" },
    ZIL: { name: "", url: "" },
    BTG: { name: "", url: "" },
    KAVA: { name: "", url: "" },
    STEEM: { name: "", url: "" },
    MFT: { name: "", url: "" },
    QKC: { name: "", url: "" },
    DOT: { name: "", url: "" },
    GLM: { name: "", url: "" },
    XEM: { name: "", url: "" },
    LOOM: { name: "", url: "" },
    BORA: { name: "", url: "" },
    SXP: { name: "", url: "" },
    NEO: { name: "", url: "" },
    AERGO: { name: "", url: "" },
    STX: { name: "", url: "" },
    VET: { name: "", url: "" },
    HBAR: { name: "", url: "" },
    WAXP: { name: "", url: "" },
    JST: { name: "", url: "" },
    UPP: { name: "", url: "" },
    GMT: { name: "", url: "" },
    AVAX: { name: "", url: "" },
    ANKR: { name: "", url: "" },
    NU: { name: "", url: "" },
    SRM: { name: "", url: "" },
    ORBS: { name: "", url: "" },
    STORJ: { name: "", url: "" },
    STPT: { name: "", url: "" },
    HUM: { name: "", url: "" },
    TFUEL: { name: "", url: "" },
    AAVE: { name: "", url: "" },
    MTL: { name: "", url: "" },
    ARK: { name: "", url: "" },
    POWR: { name: "", url: "" },
    BSV: { name: "", url: "" },
    STRAX: { name: "", url: "" },
    STMX: { name: "", url: "" },
    CVC: { name: "", url: "" },
    RFR: { name: "", url: "" },
    THETA: { name: "", url: "" },
    ENJ: { name: "", url: "" },
    ONG: { name: "", url: "" },
    IOTA: { name: "", url: "" },
    SNT: { name: "", url: "" },
    T: { name: "", url: "" },
    TT: { name: "", url: "" },
    GAS: { name: "", url: "" },
    ZRX: { name: "", url: "" },
    ELF: { name: "", url: "" },
    MED: { name: "", url: "" },
    XTZ: { name: "", url: "" },
    LSK: { name: "", url: "" },
    BTT: { name: "", url: "" },
    AQT: { name: "", url: "" },
    SSX: { name: "", url: "" },
    DAWN: { name: "", url: "" },
    SBD: { name: "", url: "" },
    ARDR: { name: "", url: "" },
    DKA: { name: "", url: "" },
    ARDR: { name: "", url: "" },
    DKA: { name: "", url: "" },
    MOC: { name: "", url: "" },
    MLK: { name: "", url: "" },
    ONT: { name: "", url: "" },
    CELO: { name: "", url: "" },
    OMG: { name: "", url: "" },
    CBK: { name: "", url: "" },
    SC: { name: "", url: "" },
    ICX: { name: "", url: "" },
    IQ: { name: "", url: "" },
    BAT: { name: "", url: "" },
    META: { name: "", url: "" },
    TON: { name: "", url: "" },
    IOST: { name: "", url: "" },
  },
};
